<a href="https://colab.research.google.com/github/TeraneAgaeva/python_for_ds_tasks/blob/main/Agaeva_%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

**Рішення 1.1:**

In [25]:
import random

In [26]:

# створюємо пустий список
random_list_uniform = []
# Генеруєм 10 випадкових чисел от 0 до 1
for _ in range(10):
    random_list_uniform.append(random.uniform(0, 1))

# Перетворимо список в NumPy вектор
vector_uniform = np.array(random_list_uniform)

print("--- Варіант 1: random.uniform ---")
print("Вектор:\n", vector_uniform)
print("Розмірність вектора:", vector_uniform.shape)
print("Тип даних елементів:", vector_uniform.dtype)

--- Варіант 1: random.uniform ---
Вектор:
 [0.50121985 0.71916535 0.0430252  0.25427881 0.92339383 0.06589209
 0.53367839 0.61245828 0.44322704 0.39011153]
Розмірність вектора: (10,)
Тип даних елементів: float64


**Рішення 1.2:**

In [23]:
#такий спосіб не створює вектор з випадкових величин. Вивоидть значення з однаковим кроком
vect= np.linspace(0, 1, 10)
print("Не випадкові рандомні величини", vect)

Не випадкові рандомні величини [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [28]:
vector_random = np.random.rand(10)
print("--- Варіант 2:  np.random.rand ---")
print("Вектор:\n", vector_random)
print("Розмірність вектора:", vector_random.shape)
print("Тип даних елементів:", vector_random.dtype)

--- Варіант 2:  np.random.rand ---
Вектор:
 [0.69928203 0.35176762 0.43804656 0.60803461 0.0408863  0.92516104
 0.78478796 0.51005478 0.91841771 0.97169543]
Розмірність вектора: (10,)
Тип даних елементів: float64


**Рішення 2:**

In [20]:
vector = np.array([11, 14, 17])
print("Вектор", vector, "розмір вектора", vector.shape, sep='\n')

Вектор
[11 14 17]
розмір вектора
(3,)


In [18]:
# матриця:
matrix = np.array(
    [[11, 14, 17],
     [20, 23, 26],
     [29, 32, 35]])
print("Матриця", matrix, "розмір матриці", matrix.shape, sep='\n')

Матриця
[[11 14 17]
 [20 23 26]
 [29 32 35]]
розмір матриці
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


**Рішення 2.1:**

In [40]:
# додавання до вектора
vector10 = vector + 10
vector10

array([21, 24, 27])

In [35]:
# округлення вектора
vector_random_round = np.round(vector_random,2)
vector_random_round

array([0.7 , 0.35, 0.44, 0.61, 0.04, 0.93, 0.78, 0.51, 0.92, 0.97])

**Рішення 2.2:**

In [38]:
# множення матриці на число
matrix2 = matrix*2
matrix2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

**Рішення 2.3:**

In [41]:
# приведення до квадрату значень вектора
vector_kvadrat = vector**2
vector_kvadrat

array([121, 196, 289])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [43]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

**Рішення 3.1:**

In [47]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

**Рішення 3.2:**

Коли домножите result_matrix на вектор C то буде 1 х 2

In [52]:
# має виконуватись правило - кількість колонок в першій матриці має дорівнювати кількості рядків у другій. Тобто можемо тільки result_matrix*C, навпаки не можемо
result_matrix1 = np.dot(result_matrix, C)
result_matrix1

array([[0.5202],
       [0.2846]])

**Рішення 3.3:**

Коли домножити result_matrix на матрицю D, то буде матриця розмірністю 2Х2

In [53]:
result_matrix2 = np.dot(result_matrix, D)
result_matrix2

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




**Рішення 4.1:**

In [54]:
print(result_matrix.T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


**Рішення 4.2:**

In [55]:
print(vector.T) #нова структура не утворилась

[11 14 17]


**Рішення 4.3:**

In [57]:
column_vector = np.expand_dims(vector, axis=1) #нова структура утворилась. був вектор а стала матриця
column_vector

array([[11],
       [14],
       [17]])

**Рішення 4.4:**

In [58]:
print(column_vector.T)

[[11 14 17]]
